<?php

define('ROLE_SUPER_ADMIN', 'super_admin');
define('ROLE_OWNER', 'owner');
define('ROLE_ADMIN', 'admin');
define('ROLE_OPERATOR', 'operator');
define('ROLE_CUSTOMER', 'customer');

define('PERMISSION_MANAGE_SHOP', 'manage_shop');
define('PERMISSION_MANAGE_OPERATORS', 'manage_operators');
define('PERMISSION_VIEW_CUSTOMERS', 'view_customers');
define('PERMISSION_CREATE_CUSTOMERS', 'create_customers');
define('PERMISSION_EDIT_CUSTOMERS', 'edit_customers');
define('PERMISSION_DELETE_CUSTOMERS', 'delete_customers');
define('PERMISSION_VIEW_DOCUMENTS', 'view_documents');
define('PERMISSION_CREATE_DOCUMENTS', 'create_documents');
define('PERMISSION_EDIT_DOCUMENTS', 'edit_documents');
define('PERMISSION_VOID_DOCUMENTS', 'void_documents');
define('PERMISSION_MANAGE_TEMPLATES', 'manage_templates');
define('PERMISSION_MANAGE_CERTIFICATES', 'manage_certificates');
define('PERMISSION_VIEW_REPORTS', 'view_reports');
define('PERMISSION_MANAGE_SETTINGS', 'manage_settings');
define('PERMISSION_MANAGE_BILLING', 'manage_billing');
define('PERMISSION_MANAGE_USERS', 'manage_users');
define('PERMISSION_MANAGE_ROLES', 'manage_roles');
define('PERMISSION_MANAGE_PERMISSIONS', 'manage_permissions');
define('PERMISSION_VIEW_AUDIT_LOGS', 'view_audit_logs');
define('PERMISSION_INVITE_STAFF', 'invite_staff');
define('PERMISSION_MANAGE_STAFF_PERMISSIONS', 'manage_staff_permissions');
define('PERMISSION_IMPORT_CUSTOMERS', 'import_customers');
define('PERMISSION_EXPORT_CUSTOMERS', 'export_customers');
define('PERMISSION_MANAGE_SHOP_SETTINGS', 'manage_shop_settings');

define('PERMISSION_VIEW_SERVICES', 'view_services');
define('PERMISSION_CREATE_SERVICES', 'create_services');
define('PERMISSION_EDIT_SERVICES', 'edit_services');
define('PERMISSION_DELETE_SERVICES', 'delete_services');
define('PERMISSION_MANAGE_SERVICE_CATEGORIES', 'manage_service_categories');

define('PERMISSION_VIEW_ORDERS', 'view_orders');
define('PERMISSION_CREATE_ORDERS', 'create_orders');
define('PERMISSION_UPDATE_ORDERS', 'update_orders');
define('PERMISSION_DELETE_ORDERS', 'delete_orders');
define('PERMISSION_CHANGE_ORDER_STATUS', 'change_order_status');
define('PERMISSION_PRINT_ORDERS', 'print_orders');

define('PERMISSION_VIEW_TRANSACTIONS', 'view_transactions');
define('PERMISSION_CREATE_TRANSACTIONS', 'create_transactions');
define('PERMISSION_REFUND_TRANSACTIONS', 'refund_transactions');

$GLOBALS['role_permissions'] = [
    ROLE_OWNER => [
        PERMISSION_MANAGE_SHOP,
        PERMISSION_MANAGE_OPERATORS,
        PERMISSION_VIEW_CUSTOMERS,
        PERMISSION_CREATE_CUSTOMERS,
        PERMISSION_EDIT_CUSTOMERS,
        PERMISSION_DELETE_CUSTOMERS,
        PERMISSION_IMPORT_CUSTOMERS,
        PERMISSION_EXPORT_CUSTOMERS,
        PERMISSION_VIEW_DOCUMENTS,
        PERMISSION_CREATE_DOCUMENTS,
        PERMISSION_EDIT_DOCUMENTS,
        PERMISSION_VOID_DOCUMENTS,
        PERMISSION_MANAGE_TEMPLATES,
        PERMISSION_MANAGE_CERTIFICATES,
        PERMISSION_VIEW_REPORTS,
        PERMISSION_MANAGE_SETTINGS,
        PERMISSION_MANAGE_SHOP_SETTINGS,
        PERMISSION_MANAGE_BILLING,
        PERMISSION_INVITE_STAFF,
        PERMISSION_MANAGE_STAFF_PERMISSIONS,
        PERMISSION_VIEW_SERVICES,
        PERMISSION_CREATE_SERVICES,
        PERMISSION_EDIT_SERVICES,
        PERMISSION_DELETE_SERVICES,
        PERMISSION_MANAGE_SERVICE_CATEGORIES,
        PERMISSION_VIEW_ORDERS,
        PERMISSION_CREATE_ORDERS,
        PERMISSION_UPDATE_ORDERS,
        PERMISSION_DELETE_ORDERS,
        PERMISSION_CHANGE_ORDER_STATUS,
        PERMISSION_PRINT_ORDERS,
        PERMISSION_VIEW_TRANSACTIONS,
        PERMISSION_CREATE_TRANSACTIONS,
        PERMISSION_REFUND_TRANSACTIONS,
    ],
    ROLE_ADMIN => [
        PERMISSION_MANAGE_OPERATORS,
        PERMISSION_VIEW_CUSTOMERS,
        PERMISSION_CREATE_CUSTOMERS,
        PERMISSION_EDIT_CUSTOMERS,
        PERMISSION_DELETE_CUSTOMERS,
        PERMISSION_VIEW_DOCUMENTS,
        PERMISSION_CREATE_DOCUMENTS,
        PERMISSION_EDIT_DOCUMENTS,
        PERMISSION_VOID_DOCUMENTS,
        PERMISSION_MANAGE_TEMPLATES,
        PERMISSION_MANAGE_CERTIFICATES,
        PERMISSION_VIEW_REPORTS,
        PERMISSION_MANAGE_SETTINGS,
        PERMISSION_MANAGE_SHOP_SETTINGS,
        PERMISSION_VIEW_SERVICES,
        PERMISSION_CREATE_SERVICES,
        PERMISSION_EDIT_SERVICES,
        PERMISSION_DELETE_SERVICES,
        PERMISSION_MANAGE_SERVICE_CATEGORIES,
        PERMISSION_VIEW_ORDERS,
        PERMISSION_CREATE_ORDERS,
        PERMISSION_UPDATE_ORDERS,
        PERMISSION_CHANGE_ORDER_STATUS,
        PERMISSION_PRINT_ORDERS,
        PERMISSION_VIEW_TRANSACTIONS,
        PERMISSION_CREATE_TRANSACTIONS,
        PERMISSION_REFUND_TRANSACTIONS,
    ],
    ROLE_OPERATOR => [
        PERMISSION_VIEW_CUSTOMERS,
        PERMISSION_CREATE_CUSTOMERS,
        PERMISSION_EDIT_CUSTOMERS,
        PERMISSION_VIEW_DOCUMENTS,
        PERMISSION_CREATE_DOCUMENTS,
        PERMISSION_VIEW_SERVICES,
        PERMISSION_CREATE_SERVICES,
        PERMISSION_EDIT_SERVICES,
        PERMISSION_VIEW_ORDERS,
        PERMISSION_CREATE_ORDERS,
        PERMISSION_UPDATE_ORDERS,
        PERMISSION_CHANGE_ORDER_STATUS,
        PERMISSION_PRINT_ORDERS,
        PERMISSION_CREATE_TRANSACTIONS,
    ],
    ROLE_CUSTOMER => [
        PERMISSION_VIEW_DOCUMENTS,
    ],
];